language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
before_script:
- npm run build
script:
- npm run test:cov
- npm run lint:all
- npx embedme README.md --verify
- npm run coveralls-report
before_deploy:
- CURRENT_VERSION=$(npm run version --silent)
- npx typedoc --out "ts-docs/$CURRENT_VERSION" src
- touch ./ts-docs/.nojekyll
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/github-pages.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/uploadArchives.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
