language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
before_script:
- npm run build
script:
- npm run test:cov
- npm run lint:all
- npx embedme README.md --verify
- npm run coveralls-report
before_deploy:
- npx typedoc --out ts-docs src
- touch ./ts-docs/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ts-docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master
